### PR TITLE
express-ts-mock example corrections

### PR DESCRIPTION
**Pull request by Codermar**
- Add .history to .gitignore
- Add @types/jest to avoid errors out of the box. Updated jest
- Change port number to something less common than 9000

### CODE REVIEW

**Comment by anttiviljami** [comment]
Hi!

Can you explain the rationale behind these changes?

> Add .history to .gitignore

What does .history have to do with openapi-backend or the express example? Why does it need to be ignored specifically instead of global .gitignore?

> Add @types/jest to avoid errors out of the box. Updated jest

This one I'm fine with. 

> Change port number to something less common than 9000

Why?

**Comment by Codermar** [comment]
I agree about .gitignore. Will remove
As for the port, I did it to improve the on-boarding to this package. 9000 is much more commonly used and in my first attempt to use the examples it did not run because it was used. I thought about making it configurable but it would add code to the examples. If you agree I can also change it elsewhere in the examples.

**Comment by anttiviljami** [comment]
Sorry to be such a stickler about this but I still don't agree with this change. 9091 just feels very arbitrary to me. Port 9000 is a commonly used port for exactly the reason that it's a standard port to do http development locally, so I'd like to keep it that way. It's pretty easy for anyone to change the port anyways.

**Comment by anttiviljami** [comment]
I did however grab commit 7ca9f09 from your branch. Thanks! :)

**Pull request closed without merging**
