### PR TITLE
Fix request parsing

### PR DESCRIPTION
**Pull request by Galiley**
Split already parsed query parameters by the Application (Express for instance)

### CODE REVIEW

**Comment by anttiviljami** [comment]
Hi @Galiley, could you explain the rationale for the first change?

Maybe add a test to explain the case you’re fixing with this change

**Comment by Galiley** [comment]
The reason behind that is kinda related to #144

**Comment by anttiviljami** [comment]
Any chance you could device a test that demonstrates this to document better what's being fixed?

Since this change affects how all requests are parsed and while I don't see any huge issues here, I'm a little uncomfortable merging without fully understanding the need for this change.

**Comment by anttiviljami** [comment]
Sorry, I'm really struggling to understand what problem this PR is solving so I've decided to close it. Feel free to reopen and give a better explanation of why this is needed.

**Pull request closed without merging**
